services:
  - type: web
    name: lexo-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: ./lexo-backend
    healthCheckPath: /

  - type: static
    name: lexo-frontend
    plan: free
    buildCommand: "npm install && npm run build"
    publishPath: "dist"
    rootDir: ./lexo-frontend
    routes:
      - type: rewrite
        source: /api/:path
        destination: https://lexo-backend.onrender.com/api/:path
      - type: rewrite
        source: /*
        destination: /index.html