"""Add countdown status to RoomStatus enum

Revision ID: 11afebfa9378
Revises: cf5ed0a7032d
Create Date: 2025-07-30 16:48:21.007124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11afebfa9378'
down_revision: Union[str, Sequence[str], None] = 'cf5ed0a7032d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, enum values are handled at the application level
    # No database schema changes needed
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###