"""Initial migration

Revision ID: a15449e2c16f
Revises: 
Create Date: 2025-10-13 15:58:29.974218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15449e2c16f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_game_ended_at_desc', 'game_history', ['ended_at'], unique=False)
    op.create_index(op.f('ix_game_history_ended_at'), 'game_history', ['ended_at'], unique=False)
    op.create_index(op.f('ix_game_history_player1_id'), 'game_history', ['player1_id'], unique=False)
    op.create_index(op.f('ix_game_history_player2_id'), 'game_history', ['player2_id'], unique=False)
    op.create_index(op.f('ix_game_history_started_at'), 'game_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_game_history_winner_id'), 'game_history', ['winner_id'], unique=False)
    op.create_index('ix_game_player1_started', 'game_history', ['player1_id', 'started_at'], unique=False)
    op.create_index('ix_game_player2_started', 'game_history', ['player2_id', 'started_at'], unique=False)
    op.create_index('ix_game_winner_ended', 'game_history', ['winner_id', 'ended_at'], unique=False)
    op.drop_constraint(op.f('user_stats_user_id_key'), 'user_stats', type_='unique')
    op.create_index('ix_stats_best_streak_desc', 'user_stats', ['best_win_streak'], unique=False)
    op.create_index('ix_stats_highest_score_desc', 'user_stats', ['highest_score'], unique=False)
    op.create_index('ix_stats_total_score_desc', 'user_stats', ['total_score'], unique=False)
    op.create_index('ix_stats_wins_desc', 'user_stats', ['wins', 'total_games'], unique=False)
    op.create_index(op.f('ix_user_stats_best_win_streak'), 'user_stats', ['best_win_streak'], unique=False)
    op.create_index(op.f('ix_user_stats_current_win_streak'), 'user_stats', ['current_win_streak'], unique=False)
    op.create_index(op.f('ix_user_stats_highest_score'), 'user_stats', ['highest_score'], unique=False)
    op.create_index(op.f('ix_user_stats_longest_word_length'), 'user_stats', ['longest_word_length'], unique=False)
    op.create_index(op.f('ix_user_stats_total_games'), 'user_stats', ['total_games'], unique=False)
    op.create_index(op.f('ix_user_stats_total_score'), 'user_stats', ['total_score'], unique=False)
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_stats_wins'), 'user_stats', ['wins'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_wins'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_total_score'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_total_games'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_longest_word_length'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_highest_score'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_current_win_streak'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_best_win_streak'), table_name='user_stats')
    op.drop_index('ix_stats_wins_desc', table_name='user_stats')
    op.drop_index('ix_stats_total_score_desc', table_name='user_stats')
    op.drop_index('ix_stats_highest_score_desc', table_name='user_stats')
    op.drop_index('ix_stats_best_streak_desc', table_name='user_stats')
    op.create_unique_constraint(op.f('user_stats_user_id_key'), 'user_stats', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_game_winner_ended', table_name='game_history')
    op.drop_index('ix_game_player2_started', table_name='game_history')
    op.drop_index('ix_game_player1_started', table_name='game_history')
    op.drop_index(op.f('ix_game_history_winner_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_started_at'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_player2_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_player1_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_ended_at'), table_name='game_history')
    op.drop_index('ix_game_ended_at_desc', table_name='game_history')
    # ### end Alembic commands ###
