"""add_user_authentication

Revision ID: b46c27f3c2b6
Revises: d3b94039fcbf
Create Date: 2025-08-01 13:42:15.627226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46c27f3c2b6'
down_revision: Union[str, Sequence[str], None] = 'd3b94039fcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_is_viewer'), 'players', ['is_viewer'], unique=False)
    op.create_index(op.f('ix_players_room_id'), 'players', ['room_id'], unique=False)
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=False)
    op.create_index(op.f('ix_rooms_created_at'), 'rooms', ['created_at'], unique=False)
    op.create_index(op.f('ix_rooms_started'), 'rooms', ['started'], unique=False)
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_started'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_created_at'), table_name='rooms')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_index(op.f('ix_players_room_id'), table_name='players')
    op.drop_index(op.f('ix_players_is_viewer'), table_name='players')
    # ### end Alembic commands ###
