"""add_game_end_time_to_rooms

Revision ID: e4918b3e6512
Revises: ff6396ee541f
Create Date: 2025-08-04 15:32:12.456709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4918b3e6512'
down_revision: Union[str, Sequence[str], None] = 'ff6396ee541f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('game_end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'game_end_time')
    # ### end Alembic commands ###
