"""Add battle royale game mode support

Revision ID: ff6396ee541f
Revises: 1ef3b1881b71
Create Date: 2025-08-04 14:29:54.636789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6396ee541f'
down_revision: Union[str, Sequence[str], None] = '1ef3b1881b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_eliminated', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('elimination_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_players_is_eliminated'), 'players', ['is_eliminated'], unique=False)
    op.add_column('rooms', sa.Column('game_mode', sa.Enum('CLASSIC', 'BATTLE_ROYALE', name='gamemode'), nullable=False))
    op.add_column('rooms', sa.Column('total_game_time', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('countdown_start_time', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('min_players', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('elimination_interval', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('players_per_elimination', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rooms_game_mode'), 'rooms', ['game_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_game_mode'), table_name='rooms')
    op.drop_column('rooms', 'players_per_elimination')
    op.drop_column('rooms', 'elimination_interval')
    op.drop_column('rooms', 'min_players')
    op.drop_column('rooms', 'countdown_start_time')
    op.drop_column('rooms', 'total_game_time')
    op.drop_column('rooms', 'game_mode')
    op.drop_index(op.f('ix_players_is_eliminated'), table_name='players')
    op.drop_column('players', 'elimination_time')
    op.drop_column('players', 'is_eliminated')
    # ### end Alembic commands ###
