// Optimize edilmiş Türkçe kelime listesi
// Daha verimli ve düzenli bir yapıya sahip
export const TURKISH_WORDS = new Set([
  // 2 harfli kelimeler
  'ev', 'at', 'el', 'su', 'aş', 'iş', 'öz', 'üç', 'iç', 'ön',
  'ada', 'aba', 'ama', 'ana', 'ata', 'ara', 'asa', 'ava', 'aşı', 'ayı',
  
  // 3 harfli kelimeler - Yaygın kullanılan
  'bal', 'bak', 'baş', 'ben', 'bey', 'bir', 'böl', 'bul', 'can', 'çay',
  'çek', 'çık', 'çok', 'dal', 'dan', 'den', 'dil', 'dış', 'düş', 'dul',
  'ebe', 'ece', 'efe', 'eke', 'evi', 'fil', 'gaz', 'gel', 'geç', 'gir',
  'göl', 'gör', 'güç', 'gül', 'güz', 'hal', 'hak', 'has', 'hay', 'hep',
  'hiç', 'hoş', 'hız', 'içi', 'ile', 'iyi', 'kal', 'kan', 'kap', 'kar',
  'kat', 'kay', 'kek', 'kem', 'kez', 'kır', 'kış', 'kiş', 'koş', 'kök',
  'köy', 'kul', 'kuş', 'lay', 'lez', 'mal', 'may', 'mış', 'nas', 'oda',
  'oya', 'ölü', 'öte', 'öze', 'pul', 'rey', 'sal', 'san', 'saç', 'sağ',
  'sel', 'sen', 'sık', 'son', 'söz', 'sus', 'süt', 'şan', 'şey', 'şık',
  'tad', 'taş', 'tel', 'tez', 'ton', 'tut', 'tüy', 'yağ', 'yak', 'yan',
  'yar', 'yas', 'yaş', 'yay', 'yaz', 'yer', 'yol', 'yon', 'yuva', 'zar', 'zor',
  
  // 4+ harfli kelimeler - En yaygın kullanılanlar
  'aday', 'adak', 'adım', 'afet', 'ağaç', 'ağır', 'akıl', 'alan', 'alev', 'alın',
  'anne', 'arap', 'asker', 'aslan', 'ateş', 'ayak', 'ayna', 'baba', 'bacak', 'bağ',
  'bahçe', 'bakır', 'balık', 'banka', 'barış', 'bahar', 'bebek', 'beyin', 'beyaz',
  'bilgi', 'bilet', 'bina', 'biraz', 'bitki', 'boğaz', 'boyun', 'börek', 'buğday',
  'burun', 'buzul', 'büyük', 'cami', 'ceket', 'cesur', 'cevap', 'ceviz', 'cüzdan',
  'çağ', 'çalı', 'çanta', 'çarşı', 'çatal', 'çatı', 'çelik', 'çevre', 'çiçek',
  'çilek', 'çimen', 'çocuk', 'çorap', 'çorba', 'dağ', 'dalga', 'damla', 'davet',
  'dede', 'değer', 'delik', 'deniz', 'dere', 'deri', 'derya', 'devam', 'devlet',
  'diken', 'dikkat', 'dilek', 'dişli', 'doğa', 'doğru', 'doku', 'dolap', 'dolu',
  'domuz', 'dost', 'düğme', 'düğün', 'dükkan', 'dünya', 'düşman', 'düzen', 'ebat',
  'ekmek', 'elma', 'emek', 'emin', 'emre', 'enerji', 'esir', 'eski', 'etek',
  'etki', 'evcil', 'evet', 'evlat', 'evren', 'ezan', 'fakat', 'fakir', 'fark',
  'fayda', 'fazla', 'fener', 'fidan', 'fikir', 'fırın', 'fırsat', 'fındık',
  'fincan', 'fiyat', 'gazete', 'gece', 'genel', 'genç', 'geniş', 'gerçek',
  'geri', 'geyik', 'gizli', 'göbek', 'göğüs', 'gölge', 'görev', 'götür',
  'gözlük', 'grup', 'güler', 'gümüş', 'güneş', 'günlük', 'güven', 'hafta',
  'hala', 'halı', 'halk', 'hamur', 'hangi', 'hanım', 'hapis', 'harita',
  'harman', 'hasta', 'hata', 'hatıra', 'hava', 'hayat', 'hayır', 'hayvan',
  'hazır', 'hele', 'henüz', 'heyet', 'hikaye', 'hizmet', 'hoşça', 'hukuk',
  'ışık', 'ırmak', 'ısı', 'ıslak', 'ılık', 'ilaç', 'ileri', 'ilgi', 'ilham',
  'ilim', 'ilk', 'iman', 'imdat', 'imkan', 'incir', 'inek', 'ipek', 'iplik',
  'iptal', 'isim', 'istek', 'işaret', 'işçi', 'işte', 'ithal', 'iyice',
  'iyilik', 'izin', 'izle', 'kabak', 'kabuk', 'kadar', 'kadeh', 'kadem',
  'kadın', 'kafa', 'kafes', 'kağıt', 'kahraman', 'kalem', 'kalp', 'kamera',
  'kamyon', 'kanat', 'kanun', 'kapak', 'kapı', 'karar', 'kardeş', 'karın',
  'karış', 'karma', 'kartal', 'kasap', 'kaset', 'kask', 'katar', 'katil',
  'kavak', 'kaval', 'kavga', 'kavis', 'kayak', 'kayıp', 'kayıt', 'kazan',
  'kazanç', 'kaza', 'kebap', 'kedi', 'keklik', 'kelebek', 'kelime', 'kemik',
  'kemer', 'kendi', 'kent', 'kenar', 'kereste', 'kere', 'kese', 'keser',
  'kesim', 'kesmek', 'keten', 'keyif', 'kılıç', 'kılıf', 'kına', 'kırık',
  'kırsal', 'kısa', 'kısım', 'kısır', 'kısmen', 'kısmet', 'kıta', 'kıvam',
  'kıyafet', 'kıyı', 'kıymet', 'kıymık', 'kızıl', 'kibrit', 'kilit', 'kilo',
  'kimlik', 'kimse', 'kimya', 'kira', 'kiraz', 'kirli', 'kirpi', 'kişi',
  'kitap', 'kitle', 'klima', 'koca', 'koku', 'kolay', 'kolej', 'koltuk',
  'komşu', 'konak', 'konum', 'konu', 'konuk', 'kopya', 'korkak', 'korku',
  'koro', 'koru', 'kova', 'kovan', 'koyun', 'köfte', 'köken', 'kömür',
  'köpek', 'köprü', 'köşe', 'kötü', 'kral', 'kredi', 'krem', 'krep',
  'kubbe', 'kuğu', 'kule', 'kulp', 'kültür', 'kumaş', 'kumar', 'kumsal',
  'kupa', 'kupon', 'kurak', 'kural', 'kurum', 'kuru', 'kuşak', 'kusur',
  'kutu', 'kutsal', 'kutup', 'kuvvet', 'kuyruk', 'kuzey', 'kuzgun', 'kuzu',
  'küçük', 'küfür', 'külah', 'külçe', 'küllük', 'kümes', 'küpe', 'kürek',
  'kürsü', 'kürk', 'küstah', 'küvet', 'lale', 'lamba', 'lastik', 'lazer',
  'leke', 'leziz', 'lezzet', 'lider', 'liman', 'limon', 'liste', 'loca',
  'lokanta', 'lokum', 'lüks', 'macun', 'madde', 'maden', 'mağara', 'mahalle',
  'mahkeme', 'mahluk', 'mahsul', 'makas', 'makarna', 'makbuz', 'makine',
  'maksat', 'malik', 'malzeme', 'mama', 'mana', 'manav', 'mandal', 'manda',
  'manga', 'mangal', 'manken', 'manto', 'mantar', 'manzara', 'marangoz',
  'maraton', 'marka', 'marş', 'mart', 'masal', 'masaj', 'maske', 'masa',
  'masraf', 'matbaa', 'matematik', 'mavi', 'maya', 'mayın', 'mayonez',
  'mazi', 'mecaz', 'meclis', 'medeni', 'medya', 'mektep', 'mektup', 'melek',
  'melodi', 'melon', 'memleket', 'memur', 'mendil', 'menü', 'mera', 'merak',
  'merasim', 'mercan', 'mercimek', 'merhamet', 'merkez', 'mermer', 'mesafe',
  'mesai', 'mesaj', 'meşe', 'meşgul', 'meşhur', 'meşru', 'meta', 'metin',
  'metod', 'metre', 'metro', 'mevcut', 'mevki', 'mevsim', 'meydan', 'meyve',
  'mezar', 'mezhep', 'mezun', 'mıknatıs', 'mısır', 'mızrak', 'mikrop',
  'miktar', 'millet', 'milyon', 'mimar', 'misafir', 'misal', 'misket',
  'miting', 'mobilya', 'moda', 'model', 'modern', 'mola', 'moral', 'motor',
  'mucize', 'muhalif', 'muhasebe', 'muhatap', 'muhit', 'muhtar', 'mumla',
  'muntazam', 'murad', 'murat', 'musiki', 'musluk', 'mutfak', 'mutlak',
  'mutlu', 'müdür', 'müezzin', 'mühendis', 'mühim', 'mühlet', 'mühür',
  'mükafat', 'mükemmel', 'mülk', 'mümin', 'mümkün', 'münasebet', 'mürekkep',
  'müsaade', 'müsabaka', 'müsteri', 'müşkül', 'müşterek', 'müşteri',
  'mütalaa', 'mütevazi', 'müthiş', 'müzakere', 'müze', 'müzik', 'nane',
  'nasıl', 'natür', 'nazik', 'neden', 'nefer', 'nefes', 'nefis', 'nehir',
  'neşe', 'nevi', 'niçin', 'nihayet', 'nikah', 'nimet', 'niş', 'nisan',
  'nişan', 'nota', 'numara', 'oda', 'odak', 'odun', 'ofis', 'okul', 'okur',
  'ordu', 'organ', 'orman', 'orta', 'ortaç', 'otel', 'otlak', 'otobüs',
  'otur', 'oturum', 'oyak', 'oymak', 'oynak', 'oyun', 'oyuncu', 'özgür',
  'özlem', 'paha', 'paket', 'palto', 'pamuk', 'pancar', 'panda', 'panik',
  'pano', 'papa', 'papağan', 'papaz', 'para', 'paraf', 'parça', 'park',
  'parlak', 'parti', 'paslı', 'pasta', 'patates', 'patika', 'patlak',
  'patron', 'pazar', 'pazı', 'pedagoj', 'pencere', 'perde', 'peruk',
  'peşin', 'peşte', 'petrol', 'peynir', 'pide', 'pilot', 'pipo', 'pişman',
  'piyade', 'piyano', 'piyasa', 'plaj', 'plak', 'plan', 'plastik', 'polis',
  'portakal', 'posta', 'pota', 'prens', 'prizma', 'profil', 'proje',
  'protokol', 'rahat', 'rahip', 'rakam', 'raket', 'rakip', 'randevu',
  'rapor', 'rasyonel', 'rays', 'reçel', 'reçete', 'rehber', 'reis', 'rekor',
  'resim', 'resmi', 'rıhtım', 'rica', 'ritim', 'riya', 'roman', 'romalı',
  'rota', 'rugan', 'ruhsat', 'saat', 'sabah', 'sabit', 'sabun', 'sabır',
  'saçak', 'saçma', 'sade', 'sadık', 'safa', 'safha', 'safra', 'sağlam',
  'sağlık', 'sahil', 'sahip', 'sahne', 'sahra', 'sakal', 'sakin', 'sakız',
  'saksı', 'salak', 'salata', 'saldırı', 'salon', 'salsa', 'salta', 'salvo',
  'saman', 'sanayi', 'sandal', 'sandık', 'sanel', 'saray', 'sarı', 'sarma',
  'sarmaşık', 'satır', 'satış', 'savaş', 'savcı', 'savunma', 'saya', 'sayfa',
  'sayı', 'saygı', 'sebebi', 'sebze', 'seçim', 'sefer', 'sefil', 'sekiz',
  'sektör', 'selam', 'selamet', 'sembol', 'seminer', 'semt', 'sene', 'seramik',
  'serbest', 'sergi', 'seri', 'servis', 'sesin', 'sesli', 'sever', 'sevgi',
  'seviye', 'seyahat', 'seyir', 'seyrek', 'sıcak', 'sıfat', 'sıfır', 'sınav',
  'sınıf', 'sınır', 'sıra', 'sırası', 'sırdaş', 'sırık', 'sırt', 'sıtma',
  'sıvı', 'sığınak', 'sığır', 'sibir', 'sicil', 'sigara', 'sigorta', 'silah',
  'silgi', 'silikon', 'silme', 'simge', 'simsar', 'sinema', 'sinir', 'sipariş',
  'siper', 'siren', 'sırma', 'sistem', 'siyah', 'siyasal', 'soba', 'soğan',
  'soğuk', 'sokak', 'sokuş', 'solucan', 'solunum', 'somut', 'sona', 'sonbahar',
  'sonra', 'sonuç', 'sopa', 'sorun', 'sosyal', 'soylu', 'soysal', 'sörf',
  'söylemek', 'spor', 'statü', 'stil', 'stok', 'strateji', 'stres', 'stüdyo',
  'sungu', 'sunum', 'sunuş', 'susam', 'susmak', 'suskun', 'susuz', 'sütun',
  'süvari', 'süzgeç', 'şaban', 'şafak', 'şahane', 'şahin', 'şahıs', 'şahit',
  'şakak', 'şaka', 'şakır', 'şal', 'şalter', 'şamata', 'şaman', 'şampanya',
  'şampiyon', 'şanslı', 'şapka', 'şarap', 'şarj', 'şarkı', 'şart', 'şaşırmak',
  'şaşkın', 'şato', 'şebeke', 'şecere', 'şef', 'şefkat', 'şehir', 'şehit',
  'şeker', 'şekil', 'şemsiye', 'şenlik', 'şerbet', 'şeref', 'şerit', 'şevk',
  'şiar', 'şifa', 'şifre', 'şiir', 'şike', 'şikayet', 'şile', 'şimdi',
  'şimşek', 'şinitsel', 'şirket', 'şişe', 'şişik', 'şişman', 'şive', 'şoför',
  'şölen', 'şömime', 'şömine', 'şövalye', 'şube', 'şüphe', 'şüpheli', 'şuur',
  'tabak', 'taban', 'tabe', 'tabi', 'tabiat', 'tabir', 'tabla', 'tablo',
  'tabur', 'tabut', 'taç', 'tacir', 'tahlil', 'tahmin', 'tahsil', 'tahta',
  'taka', 'takas', 'takdir', 'taklid', 'taklit', 'taksim', 'taksi', 'takvim',
  'takunya', 'takım', 'talep', 'talih', 'talim', 'tamir', 'tane', 'tanık',
  'tanım', 'tanış', 'tank', 'tanrı', 'tansiyon', 'tapu', 'tarak', 'taraf',
  'tarif', 'tarih', 'tarım', 'tarla', 'tarz', 'tasarım', 'tasdik', 'tasfiye',
  'taşıma', 'taşra', 'tatil', 'tatlı', 'tavır', 'tavla', 'tavsiye', 'tavuk',
  'tavan', 'taze', 'tazminat', 'tecrübe', 'tedavi', 'tedbir', 'teder', 'tehdit',
  'tehlike', 'tekel', 'teker', 'tekil', 'tekke', 'tekme', 'tekne', 'teknik',
  'teklif', 'tekrar', 'teks', 'teksi', 'tela', 'telafi', 'telaş', 'telefon',
  'telgraf', 'telif', 'telli', 'tema', 'temas', 'temel', 'temiz', 'temmuz',
  'tempo', 'tencere', 'tene', 'tenis', 'tenor', 'tente', 'tepki', 'tepe',
  'terakki', 'terazi', 'terbiye', 'tercih', 'tercüme', 'tereyağ', 'terk',
  'terlik', 'termal', 'terör', 'tersane', 'terzi', 'tesadüf', 'teselli',
  'tesis', 'tesir', 'teslimat', 'teslim', 'test', 'teşhis', 'teşkilat',
  'tetikçi', 'tevazu', 'teyit', 'teyze', 'tezgah', 'tıkaç', 'tıkanma',
  'tımar', 'tıpa', 'tıraş', 'tık', 'tıkırtı', 'tıknaz', 'tımar', 'tıp',
  'tıpkı', 'tibet', 'ticaret', 'tilki', 'tımarhane', 'tina', 'tinte', 'tip',
  'tirit', 'tirşe', 'titiz', 'titremek', 'tiyatro', 'tohum', 'tokaç', 'token',
  'tokmak', 'tolerans', 'tomruk', 'ton', 'tonton', 'topak', 'toparlak',
  'topik', 'toplam', 'toplantı', 'toplum', 'toprak', 'toptan', 'topuz',
  'torun', 'torba', 'torna', 'torpido', 'tost', 'toto', 'tokat', 'trafo',
  'trajik', 'tramva', 'traktör', 'transfer', 'trap', 'traş', 'tren', 'tribün',
  'tropik', 'trompet', 'tuğla', 'tuğra', 'tuhaflık', 'tunus', 'turist',
  'turna', 'turne', 'turnike', 'turşu', 'turuncu', 'tut', 'tutanak', 'tutar',
  'tutkun', 'tutma', 'tutmuş', 'tutum', 'tutsak', 'tuttu', 'tuvalet', 'tuz',
  'tuzak', 'tüccor', 'tüfek', 'tükenmek', 'tüketim', 'tükürük', 'tül', 'tüm',
  'tümce', 'tünel', 'tüp', 'tür', 'türbe', 'türkiye', 'türkü', 'tüten',
  'tütün', 'tüy', 'tüze', 'ucuz', 'uçak', 'uçmak', 'uçurum', 'uçuş', 'ufak',
  'ufuk', 'uğramak', 'uğraş', 'uğru', 'uğur', 'uğursuz', 'ukalık', 'ulu',
  'ulusal', 'umma', 'umre', 'umut', 'umursamak', 'unutmak', 'usanmak', 'uslu',
  'ustalık', 'usul', 'utanmak', 'uyarı', 'uydu', 'uygar', 'uygun', 'uyku',
  'uyluk', 'uymak', 'uysal', 'uysalık', 'uyuşmak', 'uzak', 'uzaklaşmak',
  'uzam', 'uzamlık', 'uzamsal', 'uzatmak', 'uzay', 'uzlaşma', 'uzman',
  'uzun', 'uzuv', 'üç', 'üçgen', 'üçlü', 'üçüncü', 'üflemek', 'ülke', 'ülker',
  'ülkü', 'ülser', 'ümit', 'ümmet', 'ün', 'üniformcı', 'ünite', 'üniversite',
  'ünlem', 'ünlü', 'ünsiyet', 'üretim', 'üretken', 'ürkmek', 'ürküntü',
  'ürküş', 'ürkmek', 'ürün', 'üst', 'üstün', 'üşümek', 'üşütmek', 'üşüşmek',
  'ütmek', 'ütopya', 'üvey', 'üzere', 'üzerinde', 'üzücü', 'üzüm', 'üzüntü',
  'vade', 'vaiz', 'vaka', 'vakit', 'vakıf', 'vali', 'vals', 'valiz', 'vanilya',
  'var', 'vapur', 'vardiya', 'varis', 'varış', 'varlık', 'varoş', 'varsayım',
  'vatan', 'vatandaş', 'vav', 'vay', 'veba', 'vecd', 'veda', 'vefa', 'vefat',
  'vehim', 'vekalet', 'vekil', 'veled', 'veli', 'velinimet', 'veraset',
  'verdim', 'verem', 'vergi', 'veri', 'verimli', 'veriş', 'vermek', 'verses',
  'vesaire', 'vesika', 'vesile', 'veta', 'veteriner', 'veto', 'veya', 'vezir',
  'vezne', 'vıcık', 'vıdı', 'vınlama', 'vidola', 'vicdan', 'video', 'vilayot',
  'virüs', 'viski', 'vitamin', 'vitrin', 'vites', 'vize', 'vizyon', 'voku',
  'voli', 'voltaj', 'vulgar', 'vurdum', 'vurgulamak', 'vurma', 'vurmak',
  'vuruş', 'vücut', 'yaban', 'yabanıl', 'yabancı', 'yağlı', 'yağma', 'yağmur',
  'yahut', 'yakalama', 'yakin', 'yakınlaşmak', 'yakıt', 'yaklaşık', 'yakut',
  'yakışık', 'yakma', 'yakmak', 'yalan', 'yalın', 'yalıtım', 'yalnız',
  'yalvaç', 'yama', 'yamak', 'yamul', 'yamyam', 'yang', 'yangın', 'yani',
  'yanık', 'yanılgı', 'yanıt', 'yankı', 'yanlış', 'yansıma', 'yapa', 'yapay',
  'yapı', 'yapıcı', 'yapım', 'yapış', 'yapıt', 'yapma', 'yapmak', 'yaprak',
  'yara', 'yaradılış', 'yaral', 'yaralar', 'yarasa', 'yaratıcı', 'yaratık',
  'yaratma', 'yaratmak', 'yardan', 'yardım', 'yardımcı', 'yare', 'yarı',
  'yarık', 'yarım', 'yarın', 'yarış', 'yarma', 'yarmak', 'yasa', 'yasak',
  'yasal', 'yasallaşma', 'yasama', 'yasamak', 'yasama', 'yaşam', 'yaşamak',
  'yaşar', 'yaşça', 'yaşlı', 'yassı', 'yastık', 'yat', 'yatağan', 'yatak',
  'yatay', 'yatırım', 'yatış', 'yatmak', 'yavaş', 'yavan', 'yaver', 'yavru',
  'yavuz', 'yaya', 'yayım', 'yayın', 'yayınlama', 'yayınlanma', 'yayırtlak',
  'yaylaç', 'yayla', 'yaymak', 'yazarlar', 'yazgı', 'yazı', 'yazıcı',
  'yazık', 'yazılı', 'yazım', 'yazın', 'yazış', 'yazıt', 'yazlık', 'yazma',
  'yazmak', 'yedek', 'yedi', 'yedirmek', 'yeğen', 'yeğin', 'yeğlemek',
  'yeğleme', 'yeğni', 'yekpare', 'yele', 'yelek', 'yelken', 'yelmek',
  'yeltenme', 'yemek', 'yemiş', 'yemle', 'yemlik', 'yen', 'yengi', 'yeni',
  'yenilik', 'yenilme', 'yenmek', 'yere', 'yerel', 'yerk', 'yerle', 'yerleşim',
  'yerleşme', 'yerli', 'yerme', 'yersen', 'yeryüzü', 'yeşil', 'yeşilli',
  'yetenek', 'yeterli', 'yetim', 'yetime', 'yetinme', 'yetişmek', 'yetke',
  'yetkeli', 'yetkin', 'yetmek', 'yetmişi', 'yetkili', 'yiğit', 'yığın',
  'yığma', 'yıkan', 'yıkılma', 'yıkım', 'yıkma', 'yılbaşı', 'yıldırım',
  'yıldız', 'yılgı', 'yılın', 'yıllık', 'yılmak', 'yıprak', 'yıpranan',
  'yırtıcı', 'yırtık', 'yırtım', 'yırtınç', 'yırtma', 'yırtmak', 'yırtpara',
  'yitik', 'yitim', 'yitmek', 'yitirmek', 'yobaz', 'yoğrulmak', 'yoğun',
  'yoğurt', 'yoklama', 'yoksa', 'yoksul', 'yokuş', 'yolcu', 'yolda', 'yolla',
  'yolluk', 'yolsuz', 'yomca', 'yonca', 'yonga', 'yontma', 'yontmak', 'yontu',
  'yörünge', 'yorum', 'yorulmak', 'yosma', 'yosun', 'yoz', 'yozlaşma', 'yöney',
  'yönel', 'yönelim', 'yönem', 'yönerge', 'yönet', 'yönetici', 'yönetim',
  'yönetmen', 'yöntem', 'yöre', 'yöresel', 'yörük', 'yudum', 'yufka', 'yuğ',
  'yukarı', 'yukarıda', 'yular', 'yulaf', 'yumaklık', 'yumru', 'yumruk',
  'yumuşak', 'yumurta', 'yumulma', 'yumuşama', 'yumulmak', 'yunak', 'yunus',
  'yurdabeyliği', 'yurt', 'yurttaş', 'yutan', 'yutkunma', 'yutmak', 'yuvak',
  'yuvarlamak', 'yuvarlanan', 'yuvarlantı', 'yuvarlatma', 'yuvarlaç',
  'yücelme', 'yücelik', 'yüce', 'yük', 'yüklem', 'yükleme', 'yüklemek',
  'yüklenmek', 'yüklen', 'yüksek', 'yükseliş', 'yükselme', 'yükselmek',
  'yükselti', 'yükseltme', 'yükseltmek', 'yükseklik', 'yüksel', 'yüksünme',
  'yüksünmek', 'yümrük', 'yün', 'yürek', 'yüreklendirme', 'yüreğin', 'yürü',
  'yürüklük', 'yürümek', 'yürürlük', 'yürütme', 'yürütmek', 'yürüttürücü',
  'yürüyücü', 'yürüyüş', 'yüz', 'yüzbaşı', 'yüzde', 'yüzer', 'yüzey',
  'yüzeyel', 'yüzgü', 'yüzkart', 'yüzleşme', 'yüzlü', 'yüzme', 'yüzmek',
  'yüzölçümü', 'yüzük', 'yüzükoyun', 'yüzüstü', 'yüzüşme', 'zabıta', 'zafer',
  'zafiyet', 'zağar', 'zahir', 'zahire', 'zahmet', 'zail', 'zalim', 'zaman',
  'zamir', 'zampara', 'zan', 'zanaatkar', 'zannetmek', 'zaptiye', 'zarar',
  'zarf', 'zarif', 'zart', 'zarzavat', 'zaten', 'zatürre', 'zavallı',
  'zaviş', 'zayıf', 'zekat', 'zekerce', 'zeki', 'zekiye', 'zelzele', 'zemberek',
  'zembil', 'zemin', 'zemzem', 'zenaat', 'zengin', 'zenne', 'zeplin', 'zerde',
  'zerre', 'zeval', 'zevk', 'zeyil', 'zeytin', 'zeytinyağı', 'zıbın', 'zıkkımlanma',
  'zımba', 'zımnında', 'zımni', 'zıpkın', 'zıplamak', 'zırhlamak', 'zırıltı',
  'zırva', 'zıt', 'zıtlaşma', 'zıvanadan', 'zibidi', 'zifiri', 'zifos',
  'zigot', 'zihaf', 'zihin', 'zikir', 'zikzak', 'zilizurnası', 'zillet',
  'zımni', 'zincir', 'zincirlemek', 'zinde', 'zinhar', 'zirai', 'zirve',
  'ziya', 'ziyan', 'ziyafet', 'ziyaret', 'ziynetli', 'zoğ', 'zoka', 'zon',
  'zor', 'zoraki', 'zorbalık', 'zorla', 'zorlamak', 'zorlanma', 'zorluk',
  'zorluğu', 'zorum', 'zovâl', 'zuhur', 'zula', 'zulüm', 'zümre', 'zümrüt',
  'züppe', 'zürafa', 'zürriyet'
]);

export const isValidWord = (word: string): boolean => {
  return TURKISH_WORDS.has(word.toLowerCase());
};
